# Dagger workspace configuration
# Install modules with: dagger module install <module>
# Example:
#   dagger module install dagger.io/linux/wolfi

[modules]

[modules.go-sdk]
source = "dagger.io/sdk/go"

[sdks.go]
module = "go-sdk"

[modules.terraform-docs]
source = ".dagger/modules/terraform-docs"

[sdks.go.scopes.".dagger/modules/terraform-docs"]
is-module = true
name = "terraform-docs"
