// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// TerraformDocsOpts contains options for Query.TerraformDocs
type TerraformDocsOpts struct {
	// Base image used to run terraform-docs.
	//
	// Default: "quay.io/terraform-docs/terraform-docs"
	BaseImage string
	// Base image version used to run terraform-docs.
	//
	// Default: "latest"
	BaseImageVersion string
	// Filepath to terraform-docs [config](https://terraform-docs.io/how-to/configuration-file/) file.
	//
	// Default: ".terraform-docs.yaml"
	Config string
	// Module path where the docs will be generated
	//
	// Default: "."
	Path string
}

func (r *Query) TerraformDocs(ws *Workspace, opts ...TerraformDocsOpts) *TerraformDocs { // terraform-docs (../../../../../:0:0)
	assertNotNil("ws", ws)
	q := r.query.Select("terraformDocs")
	for i := len(opts) - 1; i >= 0; i-- {
		// `baseImage` optional argument
		if !querybuilder.IsZeroValue(opts[i].BaseImage) {
			q = q.Arg("baseImage", opts[i].BaseImage)
		}
		// `baseImageVersion` optional argument
		if !querybuilder.IsZeroValue(opts[i].BaseImageVersion) {
			q = q.Arg("baseImageVersion", opts[i].BaseImageVersion)
		}
		// `config` optional argument
		if !querybuilder.IsZeroValue(opts[i].Config) {
			q = q.Arg("config", opts[i].Config)
		}
		// `path` optional argument
		if !querybuilder.IsZeroValue(opts[i].Path) {
			q = q.Arg("path", opts[i].Path)
		}
	}
	q = q.Arg("ws", ws)

	return &TerraformDocs{
		query: q,
	}
}

type TerraformDocs struct { // terraform-docs (../../../../../:0:0)
	query *querybuilder.Selection

	config *string
	id     *ID
	path   *string
}

func (r *TerraformDocs) WithGraphQLQuery(q *querybuilder.Selection) *TerraformDocs {
	return &TerraformDocs{
		query: q,
	}
}

func (r *TerraformDocs) Config(ctx context.Context) (string, error) {
	if r.config != nil {
		return *r.config, nil
	}
	q := r.query.Select("config")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Generate terraform docs. You must have [.terraform-docs.yaml](https://terraform-docs.io/user-guide/configuration/) configured.
func (r *TerraformDocs) Generate() *Changeset {
	q := r.query.Select("generate")

	return &Changeset{
		query: q,
	}
}

// A unique identifier for this TerraformDocs.
func (r *TerraformDocs) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *TerraformDocs) XXX_GraphQLType() string {
	return "TerraformDocs"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *TerraformDocs) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *TerraformDocs) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *TerraformDocs) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *TerraformDocs) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = TerraformDocs{query: selectNode(dag.query, id, "TerraformDocs")}
	return nil
}

func (r *TerraformDocs) Path(ctx context.Context) (string, error) {
	if r.path != nil {
		return *r.path, nil
	}
	q := r.query.Select("path")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}
