// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"dagger/terraform-docs/internal/dagger"

	"github.com/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject interface {
	querybuilder.GraphQLMarshaller
	ID(ctx context.Context) (dagger.ID, error)
}

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r TerraformDocs) MarshalJSON() ([]byte, error) {
	var concrete struct {
		BaseImageAddress string
		Source           *dagger.Directory
		Config           string
		Path             string
	}
	concrete.BaseImageAddress = r.BaseImageAddress
	concrete.Source = r.Source
	concrete.Config = r.Config
	concrete.Path = r.Path
	return json.Marshal(&concrete)
}

func (r *TerraformDocs) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		BaseImageAddress string
		Source           *dagger.Directory
		Config           string
		Path             string
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.BaseImageAddress = concrete.BaseImageAddress
	r.Source = concrete.Source
	r.Config = concrete.Config
	r.Path = concrete.Path
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "TerraformDocs":
		switch fnName {
		case "Generate":
			var parent TerraformDocs
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*TerraformDocs).Generate(&parent), nil
		case "":
			var parent TerraformDocs
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var ws *dagger.Workspace
			if inputArgs["ws"] != nil {
				err = json.Unmarshal([]byte(inputArgs["ws"]), &ws)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg ws", err))
				}
			}
			var baseImage string
			if inputArgs["baseImage"] != nil {
				err = json.Unmarshal([]byte(inputArgs["baseImage"]), &baseImage)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg baseImage", err))
				}
			}
			var baseImageVersion string
			if inputArgs["baseImageVersion"] != nil {
				err = json.Unmarshal([]byte(inputArgs["baseImageVersion"]), &baseImageVersion)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg baseImageVersion", err))
				}
			}
			var config string
			if inputArgs["config"] != nil {
				err = json.Unmarshal([]byte(inputArgs["config"]), &config)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg config", err))
				}
			}
			var path string
			if inputArgs["path"] != nil {
				err = json.Unmarshal([]byte(inputArgs["path"]), &path)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg path", err))
				}
			}
			return New(ws, baseImage, baseImageVersion, config, path), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "":
		return dag.Module().
			WithObject(
				dag.TypeDef().WithObject("TerraformDocs", dagger.TypeDefWithObjectOpts{SourceMap: dag.SourceMap("main.go", 7, 6)}).
					WithFunction(
						dag.Function("Generate",
							dag.TypeDef().WithObject("Changeset")).
							WithDescription("Generate terraform docs. You must have [.terraform-docs.yaml](https://terraform-docs.io/user-guide/configuration/) configured.").
							WithSourceMap(dag.SourceMap("main.go", 47, 1)).
							WithGenerator()).
					WithField("Config", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.TypeDefWithFieldOpts{SourceMap: dag.SourceMap("main.go", 13, 2)}).
					WithField("Path", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.TypeDefWithFieldOpts{SourceMap: dag.SourceMap("main.go", 14, 2)}).
					WithConstructor(
						dag.Function("New",
							dag.TypeDef().WithObject("TerraformDocs")).
							WithSourceMap(dag.SourceMap("main.go", 17, 1)).
							WithArg("ws", dag.TypeDef().WithObject("Workspace"), dagger.FunctionWithArgOpts{Description: "Current workspace auto populated by Dagger", SourceMap: dag.SourceMap("main.go", 19, 2)}).
							WithArg("baseImage", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Base image used to run terraform-docs.", SourceMap: dag.SourceMap("main.go", 22, 2), DefaultValue: dagger.JSON("\"quay.io/terraform-docs/terraform-docs\"")}).
							WithArg("baseImageVersion", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Base image version used to run terraform-docs.", SourceMap: dag.SourceMap("main.go", 25, 2), DefaultValue: dagger.JSON("\"latest\"")}).
							WithArg("config", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Filepath to terraform-docs [config](https://terraform-docs.io/how-to/configuration-file/) file.", SourceMap: dag.SourceMap("main.go", 28, 2), DefaultValue: dagger.JSON("\".terraform-docs.yaml\"")}).
							WithArg("path", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Module path where the docs will be generated", SourceMap: dag.SourceMap("main.go", 31, 2), DefaultValue: dagger.JSON("\".\"")}))), nil
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
